project:
  type: book

book:
  title: "motion-data-book"
  author: "Mark Roman Miller"
  date: "9/27/2022"
  chapters:
    - index.qmd
    - myrec.qmd
    - bids.qmd
    - converting-myrec-bids.qmd
    - examples.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

execute:
  freeze: auto

