# Thinking about Space, Mathematically {#sec-space-math}

## Terminology

-   acceleration
-   velocity
-   speed
-   jerk
    -   snap, crackle, pop, etc.
-   orientation (loops back)
-   angular velocity (direction and magnitude)
-   angular acceleration (direction and magnitude)

## Representing Position

-   3d Vector. Pretty straightforward.
-   Know your coordinate basis.

## Representing Rotations

Rotations are commonly represented in one of three ways: (1) euler angles, (2) rotation matrices, and (3) quaternions.


### Tait-Bryan (Euler) Angles

- Commonly used
- Technically tait-bryan angles, usually, but often called euler angles (footnote what euler angles are)
- Live sliders example of euler angles would be cool here
- Order of angles matters
- Intrinsic vs extrinsic angles
  - intrinsic is like a robot - the rotators work
  - Extrinsic angles
- is 30 positive left-handed or right-handed

### Rotation Matrices

-   nice when you don't have a lot of them lined up by time
-   but they are pretty decent to train on (find that 6DOF paper)

### Quaternions

(3b1b video) half-angle axis

Handedness is the same as the positional axis handedness.

> I was confused earlier. For some reason, I had thought that the handedness of the quaternion's axis-angle representation could be different from the underlying positional axes, but that's not the case. As long as the quaternion multiplication is consistent, it's the same handedness as the axes themselves. The quaternion's X-value specifies a rotation from Y to Z always, it's just the positional axes that determines whether that's a left or right rotation.


